### PR TITLE
just a silly thing that puts aas around a colname

### PR DESCRIPTION
**Pull request by aidandmorrison**
let me know if it makes sense!

### CODE REVIEW

**Comment by TomBEEE** [comment]
needs more a's

**Review by TomBEEE — CHANGES_REQUESTED** [review]
more a's

**Comment by aidandmorrison** [comment]
agreed

**Review by rosseji — CHANGES_REQUESTED** [review]
Many more `a`'s need

**Comment by aidandmorrison** [comment]
how about now?

**Review by rosseji — APPROVED** [review]

**Review by TomBEEE — APPROVED** [review]
the a's have satisfied my burning hunger

**Pull request merged**
